os:
  - osx

language: csharp

before_install:
  - brew update
  
install:
  - brew cask install google-chrome
  - brew install chromedriver
  - brew install gauge
  - nuget restore
  - nuget install
  - gauge --install csharp
  - gauge --install html-report

cache:
  directories:
  - $HOME/.m2

script:
  - curl -L https://bintray.com/artifact/download/gauge/activeadmin-demo/activeadmin-demo.war -O
  - nohup java -jar activeadmin-demo.war >/dev/null 2>&1 &
  - sleep 30
  - gauge Specs
